// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc8eRL9iRAcImp1GBxa04NkqtjNrJB-W0',
    appId: '1:1062911897505:web:3966c8f12d75677e7125e0',
    messagingSenderId: '1062911897505',
    projectId: 'emergence-report-app',
    authDomain: 'emergence-report-app.firebaseapp.com',
    databaseURL: 'https://emergence-report-app-default-rtdb.firebaseio.com',
    storageBucket: 'emergence-report-app.firebasestorage.app',
    measurementId: 'G-3QZR0CZ54F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiBwRbt5dgUB6AWOHOab5MBUxohAZLBFs',
    appId: '1:1062911897505:android:cc717b0be9c7ffcd7125e0',
    messagingSenderId: '1062911897505',
    projectId: 'emergence-report-app',
    databaseURL: 'https://emergence-report-app-default-rtdb.firebaseio.com',
    storageBucket: 'emergence-report-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxjTDrHwUo6AM3M9la4nv1-yUG2djh9Ls',
    appId: '1:1062911897505:ios:74564b4192d64d177125e0',
    messagingSenderId: '1062911897505',
    projectId: 'emergence-report-app',
    databaseURL: 'https://emergence-report-app-default-rtdb.firebaseio.com',
    storageBucket: 'emergence-report-app.firebasestorage.app',
    iosBundleId: 'com.example.emergencyReportSystem',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxjTDrHwUo6AM3M9la4nv1-yUG2djh9Ls',
    appId: '1:1062911897505:ios:74564b4192d64d177125e0',
    messagingSenderId: '1062911897505',
    projectId: 'emergence-report-app',
    databaseURL: 'https://emergence-report-app-default-rtdb.firebaseio.com',
    storageBucket: 'emergence-report-app.firebasestorage.app',
    iosBundleId: 'com.example.emergencyReportSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc8eRL9iRAcImp1GBxa04NkqtjNrJB-W0',
    appId: '1:1062911897505:web:fa4c6ce5b41767947125e0',
    messagingSenderId: '1062911897505',
    projectId: 'emergence-report-app',
    authDomain: 'emergence-report-app.firebaseapp.com',
    databaseURL: 'https://emergence-report-app-default-rtdb.firebaseio.com',
    storageBucket: 'emergence-report-app.firebasestorage.app',
    measurementId: 'G-QPZVNJYGL2',
  );
}
